# Generated by Django 2.2.2 on 2019-06-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20190610_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='type',
        ),
    ]
